query GetAssignableServerRolesByServerId(
    $serverId: UUID!,
    $nameFilter: String,
    $after: String,
    $authorizeLevel: Int,
) {
    communityServerRolesByServerId(
        serverId: $serverId,
        after: $after,
        where: {
            name: { ilike: $nameFilter }
            specialRoleType: { eq: None },
            authorizeLevel:  { lte: $authorizeLevel }
        }
    ) {
        pageInfo {
            endCursor
            hasNextPage
        }

        nodes {
            id
            name
        }
    }
}