query GetDirectMessageChannels($after: String) {
    directMessageChannels(
        after: $after
        order: { conversation: { latestMessageAt: DESC } }
    ) {
        pageInfo {
            hasNextPage
            hasPreviousPage
            endCursor
        }

        nodes {
            id
            friendRequest {
                otherUser {
                    id
                    displayName
                    avatarRevision
                    effectivePresenceStatus
                }
            }
        }
    }
}