query GetServerRolesByServerId($serverId: UUID!, $nameFilter: String, $after: String) {
    communityServerRolesByServerId(
        serverId: $serverId,
        after: $after,
        where: {
            name: { ilike: $nameFilter }
        }
    ) {
        pageInfo {
            endCursor
            hasNextPage
        }

        nodes {
            id
            name
            specialRoleType
            authorizeLevel
            createdAt
            numMembers
            creatorUser {
                id
                displayName
                hasAvatar
            }
            permissions {
                permission
                state
            }
        }
    }
}