query InspectMember($id: UUID!) {
    communityServerMember(id: $id) {
        id
        createdAt
        user {
            id
            userName
            displayName
            hasAvatar
        }
        roles {
            id
            name
            authorizeLevel
            specialRoleType
        }
        authorizeInfo {
            authorizeLevel
            permissions {
                permission
                isGranted
            }
            isBanned
        }
        status
        banExpireAt
    }
}