query ServerMemberSearch($serverId: UUID!, $after: String, $search: String, $status: [MembershipStatus!]!) {
    communityServerMembersFromServerId(
        serverId: $serverId
        after: $after
        search: $search
        where: { status: { in: $status } }
    ) {
        pageInfo {
            hasNextPage
            endCursor
        }

        nodes {
            id
            user {
                id
                userName
                displayName
                hasAvatar
            }
        }
    }
}