/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRefreshResponse"];
                        "application/json": components["schemas"]["ApiResponseOfRefreshResponse"];
                        "text/json": components["schemas"]["ApiResponseOfRefreshResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/authorization-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserAuthorizationInfo"];
                        "application/json": components["schemas"]["ApiResponseOfUserAuthorizationInfo"];
                        "text/json": components["schemas"]["ApiResponseOfUserAuthorizationInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/send-verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirm-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmEmailRequest"];
                    "text/json": components["schemas"]["ConfirmEmailRequest"];
                    "application/*+json": components["schemas"]["ConfirmEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/dm/{channelId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfDmChannelSummary"];
                        "application/json": components["schemas"]["ApiResponseOfDmChannelSummary"];
                        "text/json": components["schemas"]["ApiResponseOfDmChannelSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/dm/{toUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    toUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfDirectMessageResolutionResponse"];
                        "application/json": components["schemas"]["ApiResponseOfDirectMessageResolutionResponse"];
                        "text/json": components["schemas"]["ApiResponseOfDirectMessageResolutionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Name?: string;
                        Avatar?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfServerIdentityDto"];
                        "application/json": components["schemas"]["ApiResponseOfServerIdentityDto"];
                        "text/json": components["schemas"]["ApiResponseOfServerIdentityDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfServerDetailDto"];
                        "application/json": components["schemas"]["ApiResponseOfServerDetailDto"];
                        "text/json": components["schemas"]["ApiResponseOfServerDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/channel-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChannelCategoryCreateRequest"];
                    "text/json": components["schemas"]["ChannelCategoryCreateRequest"];
                    "application/*+json": components["schemas"]["ChannelCategoryCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfChannelCategoryIdentityDto"];
                        "application/json": components["schemas"]["ApiResponseOfChannelCategoryIdentityDto"];
                        "text/json": components["schemas"]["ApiResponseOfChannelCategoryIdentityDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChannelCreateRequest"];
                    "text/json": components["schemas"]["ChannelCreateRequest"];
                    "application/*+json": components["schemas"]["ChannelCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfServerChannelIdentityDto"];
                        "application/json": components["schemas"]["ApiResponseOfServerChannelIdentityDto"];
                        "text/json": components["schemas"]["ApiResponseOfServerChannelIdentityDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/channel-categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                    categoryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRoleRequest"];
                    "text/json": components["schemas"]["CreateRoleRequest"];
                    "application/*+json": components["schemas"]["CreateRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfServerRoleDto"];
                        "application/json": components["schemas"]["ApiResponseOfServerRoleDto"];
                        "text/json": components["schemas"]["ApiResponseOfServerRoleDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/communities/{serverId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serverId: string;
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchRoleRequest"];
                    "text/json": components["schemas"]["PatchRoleRequest"];
                    "application/*+json": components["schemas"]["PatchRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfServerRoleDto"];
                        "application/json": components["schemas"]["ApiResponseOfServerRoleDto"];
                        "text/json": components["schemas"]["ApiResponseOfServerRoleDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    direction?: components["schemas"]["MessageLoadDirection"];
                    cursor?: string;
                    count: number;
                };
                header?: never;
                path: {
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfGetMessagesResponse"];
                        "application/json": components["schemas"]["ApiResponseOfGetMessagesResponse"];
                        "text/json": components["schemas"]["ApiResponseOfGetMessagesResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channelId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Body?: string;
                        Attachments?: components["schemas"]["IFormFile"][];
                        /** Format: uuid */
                        ReplyToId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                        "application/json": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                        "text/json": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{messageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    messageId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Body?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                        "application/json": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                        "text/json": components["schemas"]["ApiResponseOfTimelineMessageDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    download?: boolean;
                };
                header?: never;
                path: {
                    attachmentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/csrf/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/requests/{toUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    toUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfUserRelationshipStatus"];
                        "application/json": components["schemas"]["ApiResponseOfUserRelationshipStatus"];
                        "text/json": components["schemas"]["ApiResponseOfUserRelationshipStatus"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/requests/{toUserId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    toUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/requests/{senderUserId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    senderUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/requests/{senderUserId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    senderUserId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/unfriend/{friendId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    friendId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friend/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    name?: string;
                    offset: number;
                    count: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPaginatedResultOfDiscoverFriendSummary"];
                        "application/json": components["schemas"]["ApiResponseOfPaginatedResultOfDiscoverFriendSummary"];
                        "text/json": components["schemas"]["ApiResponseOfPaginatedResultOfDiscoverFriendSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateInvitationRequest"];
                    "text/json": components["schemas"]["CreateInvitationRequest"];
                    "application/*+json": components["schemas"]["CreateInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfstring"];
                        "application/json": components["schemas"]["ApiResponseOfstring"];
                        "text/json": components["schemas"]["ApiResponseOfstring"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invite/{invitationId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        File?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetNamesRequest"];
                    "text/json": components["schemas"]["SetNamesRequest"];
                    "application/*+json": components["schemas"]["SetNamesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/lock-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponse"];
                        "application/json": components["schemas"]["ApiResponse"];
                        "text/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/dm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    offset?: number;
                    count?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPaginatedResultOfDmConversationListItemDto"];
                        "application/json": components["schemas"]["ApiResponseOfPaginatedResultOfDmConversationListItemDto"];
                        "text/json": components["schemas"]["ApiResponseOfPaginatedResultOfDmConversationListItemDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    name?: string;
                    offset: number;
                    count: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPaginatedResultOfUserIdentityProfileDto"];
                        "application/json": components["schemas"]["ApiResponseOfPaginatedResultOfUserIdentityProfileDto"];
                        "text/json": components["schemas"]["ApiResponseOfPaginatedResultOfUserIdentityProfileDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/pending-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    name?: string;
                    offset: number;
                    count: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPaginatedResultOfPendingFriendRequestDto"];
                        "application/json": components["schemas"]["ApiResponseOfPaginatedResultOfPendingFriendRequestDto"];
                        "text/json": components["schemas"]["ApiResponseOfPaginatedResultOfPendingFriendRequestDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            error: components["schemas"]["Error"];
        };
        ApiResponseOfChannelCategoryIdentityDto: {
            data: null | components["schemas"]["ChannelCategoryIdentityDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfDirectMessageResolutionResponse: {
            data: null | components["schemas"]["DirectMessageResolutionResponse"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfDmChannelSummary: {
            data: null | components["schemas"]["DmChannelSummary"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfGetMessagesResponse: {
            data: null | components["schemas"]["GetMessagesResponse"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfLoginResponse: {
            data: null | components["schemas"]["LoginResponse"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfPaginatedResultOfDiscoverFriendSummary: {
            data: null | components["schemas"]["PaginatedResultOfDiscoverFriendSummary"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfPaginatedResultOfDmConversationListItemDto: {
            data: null | components["schemas"]["PaginatedResultOfDmConversationListItemDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfPaginatedResultOfPendingFriendRequestDto: {
            data: null | components["schemas"]["PaginatedResultOfPendingFriendRequestDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfPaginatedResultOfUserIdentityProfileDto: {
            data: null | components["schemas"]["PaginatedResultOfUserIdentityProfileDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfRefreshResponse: {
            data: null | components["schemas"]["RefreshResponse"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfServerChannelIdentityDto: {
            data: null | components["schemas"]["ServerChannelIdentityDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfServerDetailDto: {
            data: null | components["schemas"]["ServerDetailDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfServerIdentityDto: {
            data: null | components["schemas"]["ServerIdentityDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfServerRoleDto: {
            data: null | components["schemas"]["ServerRoleDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfstring: {
            data: null | string;
            error: components["schemas"]["Error"];
        };
        ApiResponseOfTimelineMessageDto: {
            data: null | components["schemas"]["TimelineMessageDto"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfUserAuthorizationInfo: {
            data: null | components["schemas"]["UserAuthorizationInfo"];
            error: components["schemas"]["Error"];
        };
        ApiResponseOfUserRelationshipStatus: {
            data: components["schemas"]["UserRelationshipStatus"];
            error: components["schemas"]["Error"];
        };
        Attachment: {
            name: string;
            /** Format: uuid */
            id: string;
            type: string;
        };
        ChannelCategoryCreateRequest: {
            name: string;
        };
        ChannelCategoryDetailDto: {
            /** Format: uuid */
            id: null | string;
            name: null | string;
            channels: components["schemas"]["ServerChannelIdentityDto"][];
        };
        ChannelCategoryIdentityDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        ChannelCreateRequest: {
            name: string;
            type: components["schemas"]["CommunityServerChannelType"];
            /** Format: uuid */
            categoryId: null | string;
        };
        /** @enum {string} */
        ChannelType: ChannelType;
        /** @enum {string} */
        CommunityServerChannelType: CommunityServerChannelType;
        ConfirmEmailRequest: {
            userId: string;
            confirmationCode: string;
        };
        CreateInvitationRequest: {
            /** Format: uuid */
            serverId: string;
            /** Format: int32 */
            maxUses: null | number;
            expireAfter: components["schemas"]["InvitationExpireAfter"];
        };
        CreateRoleRequest: {
            name: string;
        };
        DirectMessageResolutionResponse: {
            /** Format: uuid */
            channelId: string;
        };
        DiscoverFriendSummary: {
            /** Format: uuid */
            userId: string;
            userName: string;
            displayName: string;
            hasAvatar: boolean;
            status: components["schemas"]["UserRelationshipStatus"];
        };
        DmChannelSummary: {
            /** Format: uuid */
            channelId: string;
            otherUser: components["schemas"]["UserIdentityProfileDto"];
            friendRequestStatus: components["schemas"]["FriendRequestStatus"];
        };
        DmConversationListItemDto: {
            /** Format: uuid */
            channelId: string;
            userProfile: components["schemas"]["UserIdentityProfileDto"];
        };
        Error: {
            code?: null | string;
            message?: null | string;
            details?: null | string | Record<string, never>;
        };
        /** @enum {string} */
        FriendRequestStatus: FriendRequestStatus;
        GetMessagesResponse: {
            messageGroups: components["schemas"]["TimelineMessageClusterDto"][];
            users: components["schemas"]["UserIdentityProfileDto"][];
            hasMoreBefore: null | boolean;
            hasMoreAfter: null | boolean;
        };
        /** Format: binary */
        IFormFile: string;
        /** @enum {string} */
        InvitationExpireAfter: InvitationExpireAfter;
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            authorization: components["schemas"]["UserAuthorizationInfo"];
            tokenType: string;
            accessToken: string;
        };
        /** @enum {string} */
        MessageLoadDirection: MessageLoadDirection;
        PaginatedResultOfDiscoverFriendSummary: {
            elements: components["schemas"]["DiscoverFriendSummary"][];
            /** Format: int32 */
            totalCount: number;
        };
        PaginatedResultOfDmConversationListItemDto: {
            elements: components["schemas"]["DmConversationListItemDto"][];
            /** Format: int32 */
            totalCount: number;
        };
        PaginatedResultOfPendingFriendRequestDto: {
            elements: components["schemas"]["PendingFriendRequestDto"][];
            /** Format: int32 */
            totalCount: number;
        };
        PaginatedResultOfUserIdentityProfileDto: {
            elements: components["schemas"]["UserIdentityProfileDto"][];
            /** Format: int32 */
            totalCount: number;
        };
        PatchFieldOfint: number;
        PatchFieldOfstring: string;
        PatchRoleRequest: {
            name: components["schemas"]["PatchFieldOfstring"];
            authorizeLevel: components["schemas"]["PatchFieldOfint"];
            permissionStates: {
                CreateRole?: components["schemas"]["PermissionState"];
                UpdateRole?: components["schemas"]["PermissionState"];
                DeleteRole?: components["schemas"]["PermissionState"];
                CreateChannel?: components["schemas"]["PermissionState"];
                DeleteChannel?: components["schemas"]["PermissionState"];
                UpdateMemberRoles?: components["schemas"]["PermissionState"];
                ManageMembers?: components["schemas"]["PermissionState"];
                KickMembers?: components["schemas"]["PermissionState"];
                WarnMembers?: components["schemas"]["PermissionState"];
                BanMembers?: components["schemas"]["PermissionState"];
                UnbanMembers?: components["schemas"]["PermissionState"];
                ReadModerationLogs?: components["schemas"]["PermissionState"];
                CreateInvitation?: components["schemas"]["PermissionState"];
            };
        };
        PendingFriendRequestDto: {
            /** Format: uuid */
            userId: string;
            userName: string;
            displayName: string;
            hasAvatar: boolean;
            status: components["schemas"]["UserRelationshipStatus"];
        };
        /** @enum {string} */
        PermissionState: PermissionState;
        RefreshResponse: {
            authorizationInfo: components["schemas"]["UserAuthorizationInfo"];
            tokenType: string;
            accessToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            confirmPassword: string;
        };
        ServerChannelIdentityDto: {
            /** Format: uuid */
            id: string;
            name: string;
            channelType: components["schemas"]["ChannelType"];
            /** Format: uuid */
            categoryId: null | string;
        };
        ServerDetailDto: {
            name: string;
            description: null | string;
            hasAvatar: boolean;
            channelCategories: components["schemas"]["ChannelCategoryDetailDto"][];
        };
        ServerIdentityDto: {
            /** Format: uuid */
            id: string;
            name: string;
            hasAvatar: boolean;
        };
        /** @enum {string} */
        ServerPermission: ServerPermission;
        ServerRoleDto: {
            /** Format: uuid */
            id: string;
            name: string;
            permissions: {
                CreateRole?: components["schemas"]["PermissionState"];
                UpdateRole?: components["schemas"]["PermissionState"];
                DeleteRole?: components["schemas"]["PermissionState"];
                CreateChannel?: components["schemas"]["PermissionState"];
                DeleteChannel?: components["schemas"]["PermissionState"];
                UpdateMemberRoles?: components["schemas"]["PermissionState"];
                ManageMembers?: components["schemas"]["PermissionState"];
                KickMembers?: components["schemas"]["PermissionState"];
                WarnMembers?: components["schemas"]["PermissionState"];
                BanMembers?: components["schemas"]["PermissionState"];
                UnbanMembers?: components["schemas"]["PermissionState"];
                ReadModerationLogs?: components["schemas"]["PermissionState"];
                CreateInvitation?: components["schemas"]["PermissionState"];
            };
            /** Format: int32 */
            authorizeLevel: number;
        };
        SetNamesRequest: {
            userName: string;
            displayName: string;
        };
        TimelineMessageClusterDto: {
            /** Format: uuid */
            senderUserId: string;
            messages: components["schemas"]["TimelineMessageClusterItemDto"][];
        };
        TimelineMessageClusterItemDto: {
            /** Format: uuid */
            id: string;
            body: null | string;
            attachments: components["schemas"]["Attachment"][];
            /** Format: date-time */
            createdAt: string;
            replyTo: null | components["schemas"]["TimelineMessageReplyDto"];
        };
        TimelineMessageDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            senderUserId: string;
            body: null | string;
            attachments: components["schemas"]["Attachment"][];
            /** Format: date-time */
            createdAt: string;
            replyTo: null | components["schemas"]["TimelineMessageReplyDto"];
        };
        TimelineMessageReplyDto: {
            /** Format: uuid */
            messageId: string;
            /** Format: uuid */
            senderUserId: string;
            bodySnippet: null | string;
            hasMoreBody: boolean;
            /** Format: int32 */
            attachmentCount: number;
        };
        UserAuthorizationInfo: {
            /** Format: uuid */
            id: string;
            isVerified: boolean;
            isProfileSetup: boolean;
            roles: string[];
            permissions: string[];
        };
        UserIdentityProfileDto: {
            /** Format: uuid */
            id: string;
            userName: null | string;
            displayName: null | string;
            hasAvatar: boolean;
        };
        /** @enum {string} */
        UserRelationshipStatus: UserRelationshipStatus;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "text/json": components["schemas"]["LoginRequest"];
                "application/*+json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ApiResponseOfLoginResponse"];
                    "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    "text/json": components["schemas"]["ApiResponseOfLoginResponse"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "text/json": components["schemas"]["RegisterRequest"];
                "application/*+json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ApiResponse"];
                    "application/json": components["schemas"]["ApiResponse"];
                    "text/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
export enum ChannelType {
    DirectMessage = "DirectMessage",
    CommunityServerText = "CommunityServerText",
    CommunityServerVoice = "CommunityServerVoice"
}
export enum CommunityServerChannelType {
    Text = "Text",
    Voice = "Voice"
}
export enum FriendRequestStatus {
    None = "None",
    Pending = "Pending",
    Canceled = "Canceled",
    Accepted = "Accepted",
    Rejected = "Rejected"
}
export enum InvitationExpireAfter {
    FiveMinutes = "FiveMinutes",
    FifteenMinutes = "FifteenMinutes",
    ThirtyMinutes = "ThirtyMinutes",
    OneHour = "OneHour",
    TwoHours = "TwoHours",
    ThreeHours = "ThreeHours",
    SixHours = "SixHours",
    TwelveHours = "TwelveHours",
    OneDay = "OneDay",
    OneWeek = "OneWeek",
    TwoWeeks = "TwoWeeks",
    FourWeeks = "FourWeeks",
    Infinite = "Infinite"
}
export enum MessageLoadDirection {
    Before = "Before",
    After = "After",
    Around = "Around"
}
export enum PermissionState {
    Inherit = "Inherit",
    Enable = "Enable",
    Disable = "Disable"
}
export enum ServerPermission {
    CreateRole = "CreateRole",
    UpdateRole = "UpdateRole",
    DeleteRole = "DeleteRole",
    CreateChannel = "CreateChannel",
    DeleteChannel = "DeleteChannel",
    UpdateMemberRoles = "UpdateMemberRoles",
    ManageMembers = "ManageMembers",
    KickMembers = "KickMembers",
    WarnMembers = "WarnMembers",
    BanMembers = "BanMembers",
    UnbanMembers = "UnbanMembers",
    ReadModerationLogs = "ReadModerationLogs",
    CreateInvitation = "CreateInvitation"
}
export enum UserRelationshipStatus {
    Stranger = "Stranger",
    OutcomingRequest = "OutcomingRequest",
    IncomingRequest = "IncomingRequest",
    Friended = "Friended"
}
