services:
  redis:
    container_name: Conflux_Redis
    image: redis:8.10.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis

  database:
    container_name: Conflux_Database
    image: postgres:18.4-alpine3.24
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "conflux"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "conflux"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  garage:
    image: dxflrs/garage:v2.3.0
    container_name: Conflux_Garage
    ports:
      - "3900:3900"
      - "3902:3902"
    env_file:
      - "./garage/.env"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - garage-data:/var/lib/garage/data
      - garage-meta:/var/lib/garage/meta
    command: ["/garage", "-c", "/etc/garage.toml", "server"]

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: Conflux_Backend
    ports:
      - "5127:5127"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5127"
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__Database: "Host=Conflux_Database;Port=5432;Database=conflux;Username=postgres;Password=password;Include Error Detail=true;Pooling=true;"
      ConnectionStrings__Redis: "Conflux_Redis:6379,abortConnect=false"      
      Frontend__Origin: "http://localhost:5173"
      S3__ServiceURL: "http://Conflux_Garage:3900"
      S3__PreSignUrl: "http://localhost:3900"
      S3__UseHttps: false
      Services__Auth__AccessTokenDuration: 900
      Services__Auth__RefreshTokenDuration: 604800
      Services__User__MaxAvatarSizeBytes: 1048576
      Services__Messaging__MaxAttachmentSizeBytes: 10485760
    env_file:
      - "./src/backend/Conflux.WebApi/.env"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  redis-data:
  redis-insight-data:
  postgres-data:
  garage-data:
  garage-meta:
