<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Conflux.Domain\Conflux.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.4" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.103.3" />
      <PackageReference Include="FileSignatures" Version="7.3.0" />
      <PackageReference Include="Humanizer.Core" Version="3.0.10" />
      <PackageReference Include="MailKit" Version="4.18.0" />
      <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
      <PackageReference Include="MemoryPack" Version="1.21.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="StackExchange.Redis.Extensions.Core" Version="13.0.1" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.12" />
    </ItemGroup>
    
    <ItemGroup>
        <Using Include="System.Text"/>
        <Using Include="Microsoft.Extensions.Logging"/>
        <Using Include="Mediator"/>
    </ItemGroup>

</Project>
