<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Facet" Version="6.6.8" />
        <PackageReference Include="Facet.Extensions.EFCore" Version="6.6.8" />
        <PackageReference Include="Facet.Mapping.Expressions" Version="6.6.8" />
        <PackageReference Include="MemoryPack" Version="1.21.4" />
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.13" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

</Project>
